-- Migration number: 0002 	2026-03-29T20:10:00.000Z

ALTER TABLE product ADD COLUMN voice INTEGER NOT NULL DEFAULT 0;
ALTER TABLE product ADD COLUMN sms INTEGER NOT NULL DEFAULT 0;
ALTER TABLE product ADD COLUMN topup INTEGER NOT NULL DEFAULT 0;
ALTER TABLE product ADD COLUMN ip TEXT NOT NULL DEFAULT '[]';
